# Generated by Django 4.2.7 on 2026-04-11 14:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="h_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="university",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField(blank=True)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book"),
                            ("chapter", "Book Chapter"),
                            ("thesis", "Thesis"),
                            ("preprint", "Preprint"),
                            ("other", "Other"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True,
                        help_text="Journal or conference name",
                        max_length=300,
                    ),
                ),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("issue", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="ISBN"),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        help_text="PDF file of the publication",
                        null=True,
                        upload_to="publications/pdfs/",
                        validators=[api.models.validate_pdf],
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("citations", models.PositiveIntegerField(default=0)),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-publication_date"],
            },
        ),
    ]
