# Generated by Django 4.2.7 on 2026-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_h_index_user_university_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
