# Generated by Django 4.2.30 on 2026-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
