# Generated by Django 4.2.30 on 2026-04-19 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_add_project_folder_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectfile",
            options={"ordering": ["original_filename"]},
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="name",
        ),
    ]
