# Generated by Django 4.2.30 on 2026-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_simplify_project_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="publication",
            name="external_authors",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="api.externalauthor"
            ),
        ),
    ]
