# Generated by Django 4.2.30 on 2026-04-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_add_publication_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("rebuttal", "Rebuttal"),
                            ("replication", "Replication"),
                            ("retraction", "Retraction"),
                            ("correction", "Correction"),
                            ("survey", "Survey"),
                            ("meta_analysis", "Meta-analysis"),
                            ("case_study", "Case Study"),
                            ("tutorial", "Tutorial"),
                            ("benchmark", "Benchmark"),
                            ("software", "Software"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pub_tags",
                        to="api.publication",
                    ),
                ),
                (
                    "refers_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referenced_by_tags",
                        to="api.publication",
                    ),
                ),
            ],
            options={
                "unique_together": {("publication", "tag")},
            },
        ),
    ]
