# Generated by Django 4.2.30 on 2026-04-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_add_publication_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="api.projectfile",
            ),
        ),
    ]
