# Generated by Django 4.2.30 on 2026-04-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_add_publication_source_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("co_authored", "Co-authored"),
                    ("comment", "Comment"),
                    ("new_pub_subject", "New publication in followed subject"),
                    ("new_pub_keyword", "New publication matching followed keyword"),
                    ("new_pub_author", "New publication by followed author"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubjectSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("physics.cond-mat", "Condensed Matter"),
                            ("physics.hep", "High Energy Physics"),
                            ("physics.gr-qc", "General Relativity & Quantum Cosmology"),
                            ("physics.quant-ph", "Quantum Physics"),
                            ("physics.atom", "Atomic, Molecular & Optical Physics"),
                            ("physics.nuclear", "Nuclear Physics"),
                            ("physics.fluid", "Fluid Dynamics"),
                            ("physics.plasma", "Plasma Physics"),
                            ("physics.other", "Physics (Other)"),
                            ("astro.cosmology", "Cosmology"),
                            ("astro.galaxies", "Galaxies"),
                            ("astro.he", "High Energy Astrophysics"),
                            ("astro.planets", "Planetary Science"),
                            ("astro.solar", "Solar & Stellar Astrophysics"),
                            ("astro.instruments", "Astronomical Instrumentation"),
                            ("math.ag", "Algebraic Geometry"),
                            ("math.analysis", "Analysis"),
                            ("math.combinatorics", "Combinatorics"),
                            ("math.dg", "Differential Geometry"),
                            ("math.logic", "Logic & Foundations"),
                            ("math.nt", "Number Theory"),
                            ("math.probability", "Probability"),
                            ("math.topology", "Topology"),
                            ("math.other", "Mathematics (Other)"),
                            ("cs.ai", "Artificial Intelligence"),
                            ("cs.cv", "Computer Vision"),
                            ("cs.crypto", "Cryptography & Security"),
                            ("cs.db", "Databases"),
                            ("cs.ds", "Data Structures & Algorithms"),
                            ("cs.hci", "Human-Computer Interaction"),
                            ("cs.ml", "Machine Learning"),
                            ("cs.networks", "Networking"),
                            ("cs.pl", "Programming Languages"),
                            ("cs.se", "Software Engineering"),
                            ("cs.other", "Computer Science (Other)"),
                            ("bio.cell", "Cell Biology"),
                            ("bio.ecology", "Ecology & Evolution"),
                            ("bio.genomics", "Genomics & Bioinformatics"),
                            ("bio.molecular", "Molecular Biology"),
                            ("bio.neuroscience", "Neuroscience"),
                            ("bio.other", "Biology (Other)"),
                            ("med.cardiology", "Cardiology"),
                            ("med.genetics", "Medical Genetics"),
                            ("med.imaging", "Medical Imaging"),
                            ("med.oncology", "Oncology"),
                            ("med.pharmacology", "Pharmacology"),
                            ("med.public", "Public Health & Epidemiology"),
                            ("med.other", "Medicine (Other)"),
                            ("chem.organic", "Organic Chemistry"),
                            ("chem.physical", "Physical Chemistry"),
                            ("chem.materials", "Materials Science"),
                            ("chem.other", "Chemistry (Other)"),
                            ("earth.atmospheric", "Atmospheric Science"),
                            ("earth.geo", "Geophysics & Geology"),
                            ("earth.ocean", "Oceanography"),
                            ("earth.other", "Earth Sciences (Other)"),
                            ("econ.finance", "Finance & Economics"),
                            ("econ.macro", "Macroeconomics"),
                            ("econ.micro", "Microeconomics"),
                            ("econ.other", "Economics (Other)"),
                            ("soc.anthropology", "Anthropology"),
                            ("soc.linguistics", "Linguistics"),
                            ("soc.political", "Political Science"),
                            ("soc.psychology", "Psychology"),
                            ("soc.sociology", "Sociology"),
                            ("soc.other", "Social Sciences (Other)"),
                            ("stat.applied", "Applied Statistics"),
                            ("stat.methods", "Statistical Methodology"),
                            ("stat.theory", "Statistical Theory"),
                            ("eng.civil", "Civil Engineering"),
                            ("eng.electrical", "Electrical Engineering"),
                            ("eng.mechanical", "Mechanical Engineering"),
                            ("eng.other", "Engineering (Other)"),
                            ("other", "Other / Interdisciplinary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["subject"],
                "unique_together": {("user", "subject")},
            },
        ),
        migrations.CreateModel(
            name="KeywordSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["keyword"],
                "unique_together": {("user", "keyword")},
            },
        ),
    ]
